// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jultmzvxmbmpiwzfoebr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1bHRtenZ4bWJtcGl3emZvZWJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MTQ3NjgsImV4cCI6MjA2NjQ5MDc2OH0.RAc3ooc5FXgoOI46P9gJSGfRPIdOVJLyosUoeWlzyaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);